version: '3'
services:
  db:
    image: mysql
    container_name: proxy_pool_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: money
      MYSQL_USER: money
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306
    volumes:
      - /var/lib/mysql:/var/lib/mysql
      -
  redis:
    # 指定镜像
    image: redis:4
    container_name: proxy_pool_redis
    ports:
      # 端口映射
      - 6379:6379
    command:
      # 执行的命令
      redis-server

  proxy_pool:
    # 指定镜像
    image: jhao104/proxy_pool:latest
    container_name: proxy_pool
    ports:
      # 端口映射
      - 5010:5010
    environment:
      DB_CONN: redis://@proxy_pool_redis:6379/0

