app:
  host: 0.0.0.0
  port: 8888


crawler:
  tasks:
    - project: zhihu
      url: https://www.zhihu.com/people/huang-liao-57
      parser: core.parser.zhihu.people.ParserZhihuPeople
    - project: zhihu
      url: https://www.zhihu.com/people/gong-qing-tuan-zhong-yang-67
      parser: core.parser.zhihu.people.ParserZhihuPeople
    - project: zhihu
      url: https://www.zhihu.com/people/cloudycity
      parser: core.parser.zhihu.people.ParserZhihuPeople


database:
  host: localhost
  port: 3306
  user: money
  password: 123456
  dbname: money